from playwright.sync_api import sync_playwright, expect
from urllib.parse import urlparse, parse_qs
import re, json, os, math
from pathlib import Path

BASE = os.environ.get('IMOVUE_TEST_URL', 'http://127.0.0.1:4323').rstrip('/')
DATA = Path(__file__).resolve().parents[1] / 'public' / 'data'
SP_COUNT = len(json.loads((DATA / 'SP.json').read_text()))
RECIFE_HOUSES = [im['precoVenda'] for im in json.loads((DATA / 'PE.json').read_text())
                if im['cidade'] == 'RECIFE' and im['tipoImovel'] == 'Casa' and im['precoVenda'] is not None]
assert RECIFE_HOUSES, 'Este cenário requer pelo menos uma casa em Recife no catálogo.'
HOUSE_LIMIT = math.ceil(min(RECIFE_HOUSES))
with sync_playwright() as p:
    browser = p.chromium.launch(executable_path=os.environ.get('IMOVUE_TEST_CHROME', '/usr/bin/google-chrome'), headless=True, args=['--no-sandbox'])
    context = browser.new_context(viewport={'width': 390, 'height': 844})
    context.route('**/*', lambda route: route.continue_() if route.request.url.startswith(BASE + '/') else route.abort())
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    page.goto(BASE + '/')
    early_search = page.get_by_role('textbox', name='Descreva o imóvel que procura')
    early_search.fill('apartamentos até 300 mil')
    early_search.press('Enter')
    expect(page.get_by_role('status')).to_contain_text('Selecione um estado')
    assert page.url == BASE + '/'
    early_search.fill('apartamentos em São José SC até 300 mil')
    early_search.press('Enter')
    expect(page).to_have_url(re.compile(r'cidade=SAO\+JOSE'))
    expect(page.locator('select').nth(1)).to_have_value('SAO JOSE')
    page.goto(BASE + '/')
    homonym_search = page.get_by_role('textbox', name='Descreva o imóvel que procura')
    homonym_search.fill('casa em Cascavel CE')
    homonym_search.press('Enter')
    expect(page).to_have_url(re.compile('cidade=CASCAVEL.*uf=CE'))
    expect(page.locator('select').nth(1)).to_have_value('CASCAVEL')
    expect(page.get_by_role('textbox', name='Descreva o imóvel que procura')).to_be_enabled()
    page.get_by_role('textbox', name='Descreva o imóvel que procura').fill('casa em Cascavel')
    page.get_by_role('textbox', name='Descreva o imóvel que procura').press('Enter')
    expect(page.locator('select').nth(0)).to_have_value('CE')
    page.goto(BASE + '/')
    search = page.get_by_role('textbox', name='Descreva o imóvel que procura')
    search.fill('apartamento em São Paulo')
    search.press('Enter')
    expect(page.get_by_text(re.compile('estado ou na cidade'))).to_be_visible()
    assert page.url == BASE + '/'
    search.fill('apartamentos em Recife até 250 mil com 2 quartos venda direta')
    search.press('Enter')
    page.wait_for_url('**/imoveis?**')
    expect(page.locator('input[type=number]').nth(0)).to_have_value('2')
    expect(page.locator('input[type=number]').nth(2)).to_have_value('250000')
    expect(page.locator('select').nth(0)).to_have_value('PE')
    expect(page.locator('select').filter(has=page.locator('option', has_text='Venda Direta Online')).last).to_have_value('Venda Direta Online')
    search = page.get_by_role('textbox', name='Descreva o imóvel que procura')
    expect(search).to_be_visible()
    search.fill('maior desconto primeiro')
    search.press('Enter')
    expect(page.locator('input[type=number]').nth(0)).to_have_value('2')
    expect(page.locator('input[type=number]').nth(2)).to_have_value('250000')
    expect(page.locator('select').nth(3)).to_have_value('percentualDesconto,desc')
    page.get_by_role('button', name=re.compile('Remover filtro: Preço máx')).click()
    expect(page.locator('input[type=number]').nth(2)).to_have_value('')
    expect(page).not_to_have_url(re.compile('precoMax'))
    page.get_by_role('button', name='Remover filtro: Maior desconto primeiro').click()
    expect(page).to_have_url(re.compile(r'(?:\?|&)sort=(?:&|$)'))
    page.reload()
    expect(page.locator('select').nth(3)).to_have_value('')
    expect(page.locator('select').nth(0)).to_be_enabled()
    page.locator('select').nth(0).select_option('SP')
    expect(page).to_have_url(re.compile('uf=SP'))
    expect(page.locator('select').nth(1)).to_have_value('')
    expect(page.locator('input[type=number]').nth(0)).to_have_value('2')
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    print('PASS: mobile home, clarification, URL filters, refinement, chips, sort reload, UF change')

    page.get_by_role('button', name='Abrir assistente de busca').click()
    chat_input = page.get_by_role('textbox', name='Mensagem para o assistente')
    send = page.get_by_role('button', name='Enviar mensagem')
    def message(text):
        chat_input.fill(text)
        send.click()
        expect(chat_input).to_be_enabled(timeout=15000)
    message('quantos imóveis')
    expect(page.locator('.chat-panel').get_by_text(re.compile(f'Encontrei {SP_COUNT} imóveis'))).to_be_visible()
    message('casas em Recife')
    message(f'até {max(1, math.floor(min(RECIFE_HOUSES)) - 1)}')
    expect(page.locator('.chat-panel').get_by_text(re.compile('Não encontrei imóveis com todos os critérios')).last).to_be_visible()
    message(f'até {HOUSE_LIMIT}')
    message('maior desconto')
    link = page.locator('.chat-panel a[href^="/imoveis?"]').last
    params = parse_qs(urlparse(link.get_attribute('href')).query)
    assert params['uf'] == ['PE'] and params['tipoImovel'] == ['Casa']
    assert params['cidade'] == ['RECIFE'] and params['precoMax'] == [str(HOUSE_LIMIT)]
    message('agora apartamentos em SP até 300 mil')
    params = parse_qs(urlparse(page.locator('.chat-panel a[href^="/imoveis?"]').last.get_attribute('href')).query)
    assert params['uf'] == ['SP'] and params['tipoImovel'] == ['Apartamento'] and 'cidade' not in params
    message('não quero imóvel ocupado')
    expect(page.locator('.chat-panel').get_by_text(re.compile('Ocupação: imóveis sem situação informada')).last).to_be_visible()
    message('pode estar ocupado')
    params = parse_qs(urlparse(page.locator('.chat-panel a[href^="/imoveis?"]').last.get_attribute('href')).query)
    assert 'ocupado' not in params
    message('<img data-security-probe src=x onerror="window.searchInjection=true">')
    assert page.locator('[data-security-probe]').count() == 0
    assert not page.evaluate('Boolean(window.searchInjection)')
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth')
    page.screenshot(path=os.environ.get('IMOVUE_TEST_SCREENSHOT', '/tmp/imovue-search-mobile.png'), full_page=False)
    print('PASS: initial chat statistics, accumulated filters, UF switch, occupancy, safe text, mobile layout')
    assert not errors, errors

    failure_context = browser.new_context()
    failure_context.route('**/*', lambda route: route.continue_() if route.request.url.startswith(BASE + '/') else route.abort())
    failure_context.route('**/data/MG.json', lambda route: route.abort())
    failure_page = failure_context.new_page()
    failure_page.goto(BASE + '/imoveis?uf=MG')
    expect(failure_page.get_by_role('alert')).to_contain_text('Não foi possível carregar')
    failure_context.unroute('**/data/MG.json')
    failure_page.get_by_role('button', name='Tentar novamente').click()
    expect(failure_page.get_by_role('alert')).to_have_count(0)
    expect(failure_page.locator('.property-card').first).to_be_visible()
    print('PASS: failed data loading is distinguished from empty results and retry recovers')
    browser.close()
